import = ["~/.config/alacritty/themes/one_dark.toml"]

[env]
TERM = "xterm-256color"

[window]
dimensions = { columns = 120, lines = 30 }
padding = { x = 10, y = 10 }
opacity = 0.9
blur = true
decorations = "full"
dynamic_title = true

[font]
normal = { family = "MesloLGS Nerd Font Mono", style = "Regular" }
size = 14.0

[scrolling]
history = 10000
multiplier = 3

[cursor]
style = { shape = "Block", blinking = "Off" }
unfocused_hollow = true

[mouse]
hide_when_typing = true

[selection]
save_to_clipboard = true
